name: 'Kivy App to APK'
description: 'Convert Kivy app to APK'

inputs:
  python-version:
    description: 'Python version to use'
    default: '3.8'
  work-dir:
    default: '.'
    description: 'Working directory'
  buildozer-cmd:
    default: 'buildozer android debug'
    description: 'Buildozer command to use'

branding:
  color: 'green'
  icon: 'play'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        architecture: x64

    - name: Setup Java 17 (required by Gradle)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
      shell: bash

    - name: Prepare virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "Using Python version: $(python --version)"
      shell: bash

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 \
          cmake libffi-dev libssl-dev
      shell: bash

    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install Cython==0.29.33 buildozer
      shell: bash

    - name: Install requirements from requirements.txt (if exists)
      run: |
        if [ -f requirements.txt ]; then
          source venv/bin/activate
          python -m pip install -r requirements.txt
        fi
      shell: bash

    - name: Cache Buildozer dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          .buildozer
        key: buildozer-cache-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          buildozer-cache-${{ runner.os }}-

    - name: Build APK with Buildozer
      run: |
        source venv/bin/activate
        ${{ inputs.buildozer-cmd }}
      shell: bash

    - name: Build with Buildozer
      run: |
        ${{ inputs.buildozer-cmd }}
      shell: bash
